import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/layout/layout";
import YoutubePlayer from "../components/react-player/youtubePlayer";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Testing App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>hello repo for testing apps</Layout>
    </div>
  );
};

export default Home;
